### ISSUE TITLE
missing dens of air

### ISSUE THREAD

**Issue by morganemacleod** [1ozturkbe/bikesplits.jl#1]
okay quick distraction then back to work over here: I think in line 52 you need a factor of the density of air in kg/m^3 ~1.2
`@NLconstraint(m, [i=1:n], dP[i] >= (1/2*CdA) * speed[i] ^ 3)`
to
`@NLconstraint(m, [i=1:n], dP[i] >= (1/2*CdA) *rho_air* speed[i] ^ 3)`

**Comment by 1ozturkbe** [comment]
Resolved in d2eb1e5!
