### ISSUE TITLE
rolling resistance 

### ISSUE THREAD

**Issue by morganemacleod** [1ozturkbe/bikesplits.jl#3]
I think that this is correct
`@constraint(m, rrP .== rider.Crr*rider.mass*xvel) # TODO check assumption`

because  the rolling resistence is the normal component of the mass times the speed, or `rider.Crr*rider.mass*cos(gradient/100)*speed`, but `cos(gradient/100)=xvel/speed`, so the expression above makes sense :)

**Comment by 1ozturkbe** [comment]
Thanks Morgan! Will close when I get to look at this again :)

**Comment by 1ozturkbe** [comment]
Resolved in abff586!
